# Generated by Django 4.2.27 on 2025-12-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_post_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='brand',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='Default description', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='Default name', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='post',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='post',
            name='sku',
            field=models.CharField(default='SKU-DEFAULT', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
