# Generated by Django 4.2.27 on 2026-01-04 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock_quantity',
            new_name='stock',
        ),
    ]
