# Generated by Django 4.2.27 on 2026-01-08 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='in_stock',
        ),
    ]
